apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: my-namespace
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.13.5
    ports:
    - containerPort: 80
